# Generated by Django 4.2.23 on 2025-07-12 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0004_purchaseorder_confirmed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapa_tx_ref', models.CharField(help_text='Chapa transaction reference', max_length=100, unique=True)),
                ('chapa_checkout_url', models.URLField(blank=True, help_text='Chapa checkout URL', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in ETB', max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('description', models.TextField(help_text='Payment description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('chapa_response', models.JSONField(blank=True, help_text='Full Chapa API response', null=True)),
                ('webhook_data', models.JSONField(blank=True, help_text='Webhook notification data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapa_transactions', to='Inventory.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='initial', max_length=20)),
                ('order_items', models.JSONField(help_text='Cart items for this supplier')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('chapa_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_payment', to='payments.chapatransaction')),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='Inventory.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pu_status_e857f3_idx'), models.Index(fields=['user', 'status'], name='payments_pu_user_id_909b76_idx'), models.Index(fields=['supplier', 'status'], name='payments_pu_supplie_ab3ad2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_data', models.JSONField(help_text='Raw webhook payload')),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.chapatransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed'], name='payments_pa_process_b87694_idx'), models.Index(fields=['created_at'], name='payments_pa_created_83f97a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chapatransaction',
            index=models.Index(fields=['chapa_tx_ref'], name='payments_ch_chapa_t_9ef214_idx'),
        ),
        migrations.AddIndex(
            model_name='chapatransaction',
            index=models.Index(fields=['status'], name='payments_ch_status_46cd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='chapatransaction',
            index=models.Index(fields=['user', 'status'], name='payments_ch_user_id_e46495_idx'),
        ),
        migrations.AddIndex(
            model_name='chapatransaction',
            index=models.Index(fields=['supplier', 'status'], name='payments_ch_supplie_cb3fce_idx'),
        ),
    ]
