# Generated by Django 5.2.3 on 2025-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head_manager', 'Head Manager'), ('store_manager', 'Store Manager'), ('cashier', 'Cashier'), ('supplier', 'Supplier')], max_length=20),
        ),
    ]
