# Generated by Django 4.2.23 on 2025-07-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(help_text='Username/email attempted during login', max_length=150)),
                ('login_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_status', models.CharField(choices=[('success', 'Successful'), ('failed', 'Failed')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('user_role', models.CharField(blank=True, help_text='User role at time of login', max_length=20)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login', max_length=100)),
                ('user', models.ForeignKey(blank=True, help_text='User who attempted login (null for failed attempts with invalid username)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-login_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_email', models.EmailField(help_text='Previous email before reset', max_length=254)),
                ('new_email', models.EmailField(help_text='New temporary email after reset', max_length=254)),
                ('temporary_password', models.CharField(help_text='Temporary password (hashed)', max_length=128)),
                ('reset_reason', models.TextField(blank=True, help_text='Reason for account reset')),
                ('reset_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_resets_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Reset',
                'verbose_name_plural': 'Account Resets',
                'ordering': ['-reset_timestamp'],
            },
        ),
    ]
