# Generated by Django 5.2.3 on 2025-06-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_storemanager_manager_and_more'),
        ('users', '0002_customuser_is_verified_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
