# Generated by Django 5.2.3 on 2025-06-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_storemanager_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
