# Generated by Django 5.2.3 on 2025-07-06 18:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_financialrecord_cashier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storecashier',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='storecashier',
            unique_together={('store', 'cashier')},
        ),
        migrations.AddConstraint(
            model_name='storecashier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('store',), name='unique_active_cashier_per_store'),
        ),
    ]
