# Generated by Django 5.2.3 on 2025-07-10 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required_delivery_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('acknowledged', 'Acknowledged by Supplier'), ('quoted', 'Quote Provided'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Purchase Order'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('supplier_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quoted_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='Inventory.supplier')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('maximum_order_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True, help_text='Detailed product specifications')),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('color_options', models.CharField(blank=True, max_length=200)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('availability_status', models.CharField(choices=[('in_stock', 'In Stock'), ('limited_stock', 'Limited Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('pre_order', 'Pre-Order')], default='in_stock', max_length=20)),
                ('estimated_delivery_time', models.CharField(help_text="e.g., '2-3 business days', '1 week'", max_length=100)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='supplier_products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='Inventory.supplier')),
            ],
            options={
                'ordering': ['product_name'],
                'unique_together': {('supplier', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quoted_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supplier_notes', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.purchaserequest')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='Inventory.supplierproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('service_provider', 'Service Provider'), ('other', 'Other')], max_length=20)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('primary_contact_name', models.CharField(max_length=100)),
                ('primary_contact_title', models.CharField(blank=True, max_length=100)),
                ('primary_contact_phone', models.CharField(max_length=20)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('business_address_line1', models.CharField(max_length=200)),
                ('business_address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('product_categories', models.TextField(help_text='Comma-separated list of product categories supplied')),
                ('estimated_delivery_timeframe', models.CharField(help_text="e.g., '3-5 business days', '1-2 weeks'", max_length=100)),
                ('preferred_payment_terms', models.CharField(choices=[('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_45', 'Net 45 Days'), ('net_60', 'Net 60 Days'), ('cod', 'Cash on Delivery'), ('advance', 'Advance Payment'), ('credit_card', 'Credit Card')], default='net_30', max_length=20)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value in USD', max_digits=10)),
                ('business_license', models.CharField(blank=True, max_length=200)),
                ('certifications', models.TextField(blank=True, help_text='List any relevant business certifications')),
                ('insurance_details', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('onboarding_completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Inventory.supplier')),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
    ]
