# Generated by Django 5.2.3 on 2025-06-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Aggregates and Composites', 'Aggregates and Composites'), ('Masonry', 'Masonry'), ('Metals', 'Metals'), ('Wood and Wood Products', 'Wood and Wood Products'), ('Plastics and Polymers', 'Plastics and Polymers'), ('Glass and Finishing Materials', 'Glass and Finishing Materials')], default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
