# Generated by Django 5.2.3 on 2025-07-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_purchaserequest_supplierproduct_purchaserequestitem_and_more'),
    ]

    operations = [
    ]
