# Generated by Django 4.2.23 on 2025-07-12 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0003_notificationcategory_productcategory_purchaserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Head Manager who confirmed delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When delivery was confirmed by Head Manager', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Delivery address for this order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Notes from delivery confirmation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='estimated_delivery_hours',
            field=models.PositiveIntegerField(default=168, help_text='Estimated delivery time in hours (default: 7 days)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='has_issues',
            field=models.BooleanField(default=False, help_text='Whether delivery has reported issues'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='issue_reported_at',
            field=models.DateTimeField(blank=True, help_text='When issues were first reported', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='issue_reported_by',
            field=models.ForeignKey(blank=True, help_text='Head Manager who reported issues', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_order_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount in ETB', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Chapa transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='When supplier marked order as shipped', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When this item was confirmed as received', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='has_issues',
            field=models.BooleanField(default=False, help_text='Whether this item has delivery issues'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_confirmed_received',
            field=models.BooleanField(default=False, help_text='Whether this item was confirmed as received'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='issue_description',
            field=models.TextField(blank=True, help_text='Description of any issues with this item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('issue_reported', 'Issue Reported'), ('cancelled', 'Cancelled')], default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.CharField(default='ETB', max_length=3),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Inventory.purchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Order status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('issue_type', models.CharField(choices=[('missing_items', 'Missing Items'), ('damaged_items', 'Damaged Items'), ('wrong_items', 'Wrong Items'), ('quality_issues', 'Quality Issues'), ('packaging_issues', 'Packaging Issues'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(help_text='Brief description of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('issue_photos', models.JSONField(blank=True, default=list, help_text='List of photo file paths documenting the issue')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the issue was resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_items', models.ManyToManyField(blank=True, help_text='Specific items affected by this issue', related_name='issue_reports', to='Inventory.purchaseorderitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='Inventory.purchaseorder')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_delivery_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_delivery_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='General notes about the delivery')),
                ('all_items_received', models.BooleanField(default=True, help_text='Whether all items were received as expected')),
                ('delivery_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', help_text='Overall condition of delivered items', max_length=20)),
                ('delivery_photos', models.JSONField(blank=True, default=list, help_text='List of photo file paths for delivery documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_deliveries_detail', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmation', to='Inventory.purchaseorder')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
