# Generated by Django 5.2.3 on 2025-07-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_notificationcategory_productcategory_purchaserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestocktransferrequest',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='Date when transfer was completed', null=True),
        ),
        migrations.AddField(
            model_name='storestocktransferrequest',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Reason for declining the request'),
        ),
    ]
