# Generated by Django 5.2.3 on 2025-07-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_storestocktransferrequest_completed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storestocktransferrequest',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='storestocktransferrequest',
            name='decline_reason',
        ),
    ]
