# Generated by Django 5.2.3 on 2025-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_supplier_warehouseproduct_warehousestockmovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousestockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Stock Receipt'), ('issue', 'Stock Issue'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Transfer'), ('return', 'Return'), ('damage', 'Damage/Loss')], max_length=20),
        ),
    ]
