# Generated by Django 5.2.3 on 2025-07-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_warehousestockmovement_movement_type'),
    ]

    operations = [
        # Remove indexes first before removing fields/models
        migrations.RemoveIndex(
            model_name='warehousestockmovement',
            name='Inventory_w_warehou_80963f_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehousestockmovement',
            name='Inventory_w_movemen_b0a603_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehousestockmovement',
            name='Inventory_w_created_08ee4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_product_bcbdca_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_sku_3176d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_categor_03afb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_supplie_e7347e_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_is_acti_246b4d_idx',
        ),
        # Now remove fields
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='warehousestockmovement',
            name='warehouse_product',
        ),
        migrations.RemoveField(
            model_name='warehousestockmovement',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch or lot number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='floor',
            field=models.CharField(blank=True, help_text='Floor level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_product', 'Finished Product'), ('component', 'Component'), ('tool', 'Tool'), ('equipment', 'Equipment'), ('consumable', 'Consumable')], default='finished_product', help_text='Type of product', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.CharField(blank=True, help_text='Storage room', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.CharField(blank=True, help_text='Shelf location', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('custom', 'Custom Size')], help_text='Product size', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storing_condition',
            field=models.CharField(choices=[('room_temperature', 'Room Temperature'), ('cool_dry_place', 'Cool Dry Place'), ('moisture_free', 'Moisture Free'), ('temperature_sensitive', 'Temperature Sensitive'), ('electrical_safe', 'Electrical Safe Storage'), ('ceramic_safe', 'Ceramic Safe Storage'), ('chemical_safe', 'Chemical Safe Storage')], default='room_temperature', help_text='Required storage conditions', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_company',
            field=models.CharField(blank=True, help_text='Supplier company name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.CharField(blank=True, help_text='Product variation (color, model, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pipes', 'Pipes'), ('Electric Wire', 'Electric Wire'), ('Cement', 'Cement'), ('Ceramics', 'Ceramics'), ('Glass and Finishing Materials', 'Glass and Finishing Materials')], default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='Inventory_p_name_9ad0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='Inventory_p_categor_d734ee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier_company'], name='Inventory_p_supplie_185663_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['batch_number'], name='Inventory_p_batch_n_8360e0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['expiry_date'], name='Inventory_p_expiry__ceb3d0_idx'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='WarehouseProduct',
        ),
        migrations.DeleteModel(
            name='WarehouseStockMovement',
        ),
    ]
