# Generated by Django 5.2.3 on 2025-07-05 21:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_warehousestockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum storage capacity')),
                ('current_utilization', models.PositiveIntegerField(default=0, help_text='Current storage utilization')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_product_bcbdca_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_sku_3176d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_categor_03afb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_supplie_e7347e_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouseproduct',
            name='Inventory_w_is_acti_246b4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehousestockmovement',
            name='Inventory_w_warehou_80963f_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehousestockmovement',
            name='Inventory_w_movemen_b0a603_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehousestockmovement',
            name='Inventory_w_created_08ee4c_idx',
        ),
        migrations.AlterField(
            model_name='warehousestockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Stock Receipt'), ('shipment', 'Stock Shipment'), ('adjustment', 'Stock Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Return'), ('damage', 'Damage/Loss')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='Inventory.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.warehouseproduct'),
        ),
    ]
