# Generated by Django 4.2.23 on 2025-07-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_purchaseorder_confirmed_by_and_more'),
        ('Inventory', '0005_remove_storestocktransferrequest_completed_date_and_more'),
    ]

    operations = [
    ]
