# Generated by Django 5.2.3 on 2025-07-05 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_purchaseorder_purchaseorderitem_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where this product is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Inventory.warehouse'),
        ),
    ]
