# Generated by Django 5.2.3 on 2025-07-10 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_restockrequest_storestocktransferrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-bell', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower numbers = higher priority')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Categories',
                'ordering': ['priority', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('unassigned_store_manager', 'Unassigned Store Manager'), ('pending_restock_request', 'Pending Restock Request'), ('pending_transfer_request', 'Pending Transfer Request'), ('new_supplier_registration', 'New Supplier Registration'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('low_stock_alert', 'Low Stock Alert'), ('system_announcement', 'System Announcement')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('target_roles', models.JSONField(default=list, help_text='List of roles that should see this notification')),
                ('related_user_id', models.PositiveIntegerField(blank=True, help_text='ID of related user', null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL for primary action', max_length=500)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification should expire', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Inventory.notificationcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='Inventory.systemnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['notification_type'], name='Inventory_s_notific_7b3dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_active', 'created_at'], name='Inventory_s_is_acti_aa6575_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['expires_at'], name='Inventory_s_expires_28fafa_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['priority'], name='Inventory_s_priorit_0dbf54_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationstatus',
            index=models.Index(fields=['user', 'is_read'], name='Inventory_u_user_id_5e5799_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationstatus',
            index=models.Index(fields=['user', 'is_dismissed'], name='Inventory_u_user_id_b21c79_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationstatus',
            index=models.Index(fields=['notification', 'is_read'], name='Inventory_u_notific_79147a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationstatus',
            unique_together={('user', 'notification')},
        ),
    ]
