# Generated by Django 4.2.23 on 2025-07-13 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0006_merge_20250713_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_completed_date',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_initiated_date',
            field=models.DateTimeField(blank=True, help_text='When payment was initiated', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(default='pending', help_text='Payment status from Chapa', max_length=20),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_restock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity actually received by store', null=True),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='receiving_notes',
            field=models.TextField(blank=True, help_text='Notes from store manager on receipt'),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_restock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='shipped_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity shipped from warehouse', null=True),
        ),
        migrations.AddField(
            model_name='restockrequest',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when this product batch arrived in warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch number for FIFO tracking', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Final fulfilled quantity', null=True),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('received', 'Received'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase_delivery', 'Purchase Delivery'), ('restock_fulfillment', 'Restock Fulfillment'), ('sale', 'Sale'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Manual Adjustment'), ('damage', 'Damage/Loss'), ('return', 'Return')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for stock increase, negative for decrease')),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='Inventory.purchaseorder')),
                ('restock_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='Inventory.restockrequest')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='Inventory.warehouseproduct')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse_product', 'created_at'], name='Inventory_i_warehou_184051_idx'), models.Index(fields=['movement_type'], name='Inventory_i_movemen_876686_idx'), models.Index(fields=['created_at'], name='Inventory_i_created_dccbcc_idx')],
            },
        ),
    ]
