# Generated by Django 4.2.23 on 2025-07-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_enhance_warehouse_inventory_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='warehouse_product',
            field=models.ForeignKey(blank=True, help_text='The warehouse product this supplier catalog entry is based on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_catalog_entries', to='Inventory.warehouseproduct'),
        ),
    ]
