# Generated by Django 5.2.3 on 2025-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_notificationcategory_systemnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='notification_type',
            field=models.CharField(choices=[('unassigned_store_manager', 'Unassigned Store Manager'), ('empty_store', 'Empty Store'), ('pending_restock_request', 'Pending Restock Request'), ('pending_transfer_request', 'Pending Transfer Request'), ('new_supplier_registration', 'New Supplier Registration'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('low_stock_alert', 'Low Stock Alert'), ('system_announcement', 'System Announcement')], max_length=50),
        ),
    ]
