# Generated by Django 4.2.23 on 2025-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_add_warehouse_product_to_supplier_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Plumbing', 'Plumbing Supplies'), ('Electrical', 'Electrical Components'), ('Cement', 'Cement and Masonry Materials'), ('Hardware', 'Hardware and Tools'), ('Paint', 'Paint and Finishing Materials')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restockrequest',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason for restock request'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='category',
            field=models.CharField(choices=[('Plumbing', 'Plumbing Supplies'), ('Electrical', 'Electrical Components'), ('Cement', 'Cement and Masonry Materials'), ('Hardware', 'Hardware and Tools'), ('Paint', 'Paint and Finishing Materials')], max_length=100),
        ),
    ]
