# Generated by Django 4.2.23 on 2025-07-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_reason_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestocktransferrequest',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason for stock transfer request'),
        ),
    ]
