# Generated by Django 4.2.23 on 2025-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_remove_transfer_reason_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this product is active and available'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=10, help_text='Minimum stock level threshold for low stock alerts'),
        ),
    ]
