# Generated by Django 4.2.23 on 2025-07-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_product_is_active_product_minimum_stock_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity available from this supplier'),
        ),
    ]
