# Generated by Django 4.2.23 on 2025-07-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_add_stock_quantity_constraints'),
        ('Inventory', '0012_add_stock_quantity_constraints'),
    ]

    operations = [
    ]
