# Generated by Django 5.2.3 on 2025-07-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_merge_20250727_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity available from this supplier'),
        ),
    ]
