# Generated by Django 5.2.3 on 2025-07-29 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_merge_20250727_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity available from this supplier'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price must be greater than 0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
