# Generated by Django 4.2.23 on 2025-07-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_alter_supplierproduct_stock_quantity'),
        ('Inventory', '0014_alter_supplierproduct_stock_quantity_and_more'),
    ]

    operations = [
    ]
