# Generated by Django 5.2.3 on 2025-07-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_remove_warehouseproduct_supplier_and_more'),
        ('transactions', '0003_remove_order_product_remove_transaction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_orders', to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, default='Walk-in Customer', max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='receipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Banking'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
